config/routes.rb
Rails.application.routes.draw do
  resources :ninjas
  resources :dojos
  root to: "dojos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dojo.rb
class Dojo < ApplicationRecord
    has_many :ninjas, dependent: :destroy
    validates :name, :city, :state, presence: true
    validates :state, length: {minimum: 2, maximum: 2} 

   
end

app/models/ninja.rb
class Ninja < ApplicationRecord
  belongs_to :dojo
  validates :first_name, :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  before_action :set_dojo, only: %i[ show edit update destroy ]

  # GET /dojos or /dojos.json
  def index
    @dojos = Dojo.all
  end

  # GET /dojos/1 or /dojos/1.json
  def show
  end

  # GET /dojos/new
  def new
    @dojo = Dojo.new
  end

  # GET /dojos/1/edit
  def edit
  end

  # POST /dojos or /dojos.json
  def create
    @dojo = Dojo.new(dojo_params)

    respond_to do |format|
      if @dojo.save
        format.html { redirect_to @dojo, notice: "Dojo was successfully created." }
        format.json { render :show, status: :created, location: @dojo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dojos/1 or /dojos/1.json
  def update
    respond_to do |format|
      if @dojo.update(dojo_params)
        format.html { redirect_to @dojo, notice: "Dojo was successfully updated." }
        format.json { render :show, status: :ok, location: @dojo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dojos/1 or /dojos/1.json
  def destroy
    @dojo.destroy
    respond_to do |format|
      format.html { redirect_to dojos_url, notice: "Dojo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dojo
      @dojo = Dojo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dojo_params
      params.require(:dojo).permit(:name, :city, :state)
    end
end

app/controllers/ninjas_controller.rb
class NinjasController < ApplicationController
  before_action :set_ninja, only: %i[ show edit update destroy ]

  # GET /ninjas or /ninjas.json
  def index
    @ninjas = Ninja.all
  end

  # GET /ninjas/1 or /ninjas/1.json
  def show
  end

  # GET /ninjas/new
  def new
    @ninja = Ninja.new
  end

  # GET /ninjas/1/edit
  def edit
  end

  # POST /ninjas or /ninjas.json
  def create
    @ninja = Ninja.new(ninja_params)

    respond_to do |format|
      if @ninja.save
        format.html { redirect_to @ninja, notice: "Ninja was successfully created." }
        format.json { render :show, status: :created, location: @ninja }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ninjas/1 or /ninjas/1.json
  def update
    respond_to do |format|
      if @ninja.update(ninja_params)
        format.html { redirect_to @ninja, notice: "Ninja was successfully updated." }
        format.json { render :show, status: :ok, location: @ninja }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninjas/1 or /ninjas/1.json
  def destroy
    @ninja.destroy
    respond_to do |format|
      format.html { redirect_to ninjas_url, notice: "Ninja was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ninja
      @ninja = Ninja.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ninja_params
      params.require(:ninja).permit(:dojo_id, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dojos_helper.rb
module DojosHelper
end

app/helpers/ninjas_helper.rb
module NinjasHelper
end

app/views/dojos/_form.html.erb
<%= form_with(model: dojo) do |form| %>
  <% if dojo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dojo.errors.count, "error") %> prohibited this dojo from being saved:</h2>

      <ul>
        <% dojo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dojos/edit.html.erb
<h1>Editing Dojo</h1>

<%= render 'form', dojo: @dojo %>

<%= link_to 'Show', @dojo %> |
<%= link_to 'Back', dojos_path %>

app/views/dojos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dojos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dojos.each do |dojo| %>
      <tr>
        <td><%= dojo.name %></td>
        <td><%= dojo.city %></td>
        <td><%= dojo.state %></td>
        <td><%= link_to 'Show', dojo %></td>
        <td><%= link_to 'Edit', edit_dojo_path(dojo) %></td>
        <td><%= link_to 'Destroy', dojo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
    <tr>
    <td><%= link_to 'listado de ninjas', ninjas_path %></td> 
    <td><%= link_to 'New Dojo', new_dojo_path %></td>
</tr>

app/views/dojos/new.html.erb
<h1>New Dojo</h1>

<%= render 'form', dojo: @dojo %>

<%= link_to 'Back', dojos_path %>

app/views/dojos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dojo.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @dojo.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @dojo.state %>
</p>

<%= link_to 'Edit', edit_dojo_path(@dojo) %> |
<%= link_to 'Back', dojos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoNinjas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ninjas/_form.html.erb
<%= form_with(model: ninja) do |form| %>
  <% if ninja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ninja.errors.count, "error") %> prohibited this ninja from being saved:</h2>

      <ul>
        <% ninja.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dojo_id %>
    <%= form.text_field :dojo_id %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ninjas/edit.html.erb
<h1>Editing Ninja</h1>

<%= render 'form', ninja: @ninja %>

<%= link_to 'Show', @ninja %> |
<%= link_to 'Back', ninjas_path %>

app/views/ninjas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ninjas</h1>

<table>
  <thead>
    <tr>
      <th>Dojo</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ninjas.each do |ninja| %>
      <tr>
        <td><%= ninja.dojo_id %></td>
        <td><%= ninja.first_name %></td>
        <td><%= ninja.last_name %></td>
        <td><%= link_to 'Show', ninja %></td>
        <td><%= link_to 'Edit', edit_ninja_path(ninja) %></td>
        <td><%= link_to 'Destroy', ninja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ninja', new_ninja_path %>

app/views/ninjas/new.html.erb
<h1>New Ninja</h1>

<%= render 'form', ninja: @ninja %>

<%= link_to 'Back', ninjas_path %>

app/views/ninjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dojo:</strong>
  <%= @ninja.dojo_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @ninja.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @ninja.last_name %>
</p>

<%= link_to 'Edit', edit_ninja_path(@ninja) %> |
<%= link_to 'Back', ninjas_path %>